on: workflow_dispatch
name: Depoloy FPB5
jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: NPM Build
        run: |
          npm install
          npm run build
        env:
          CI: false

      - uses: sebastianpopp/ftp-action@v2.0.0
        with:
          host: 160.153.132.207
          user: fpb@fantham.co.uk
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: build
