on: workflow_dispatch
name: Depoloy FPB5
jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node 16 LTS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install from cache first
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: NPM Build
        run: |
          yarn install
          npm run build
        env:
          CI: false

      - name: Set up gCloud auth
        uses: google-github-actions/auth@v1
        with:
          project_id: fpbioimage
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gCloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: fpbioimage

      - name: Deploy app to GCP
        run: npm run deploy
